schedule:
  capture_query_stats_job:
    cron: "0 * * * *"
    class: "Pg::CaptureQueryStatsJob"
    queue: "maintenance"

  clear_query_stats_job:
    cron: "0 0 * * 0"
    class: "Pg::ClearQueryStatsJob"
    queue: "maintenance"
